### ISSUE TITLE
App not opening (Troubleshooting didn't work)

### ISSUE THREAD

**Issue by meowisme** [angelolz/CookieClickerRPC#34]
I'd love to be able to show off how I spend way too much time on Cookie Clicker to everyone on Discord but I can't get the .exe to open.
I've tried turning off my computer protection, I tried doing it with and without Cookie Clicker open, I followed the troubleshooting guide, the website, I tried reinstalling/updating Java !

Would love to know if there's something I'm just missing...

**Comment by angelolz** [comment]
Hello! Sorry to hear that you're having problems.

Please try these steps for me, :
1. **Download** the `.jar` file of the latest version [here](https://github.com/angelolz/CookieClickerRPC/releases/latest).
2. Open up **Command Prompt**.
3. Use the `cd` command to navigate to where the `.jar` file was downloaded.
![image](https://github.com/angelolz/CookieClickerRPC/assets/25342763/63ba4b94-95fa-4e0c-96e6-3736c69de32a)
4. Type in the following command: `java -jar <name of jar file>.jar` and hit **Enter**.
![image](https://github.com/angelolz/CookieClickerRPC/assets/25342763/23835da4-85f2-40b3-a6f3-381203690904)

Let me know if this works successfully for you. If there are errors that appear, please reply with them. Thanks!

**Comment by meowisme** [comment]
That worked ! Thank you so much

**Comment by meowisme** [comment]
That worked ! Thank you so much
